### ISSUE TITLE
Leetcode 

### ISSUE THREAD

**Issue by 123sriya** [31b4/Leetcode-Premium-Bypass#1] opened 2023-11-08 17:40 UTC
How to open premium membership in leetcode
![IMG-20231108-WA0014.jpg](https://github.com/31b4/Leetcode-Premium-Bypass/assets/150028588/8e50aba9-6971-409a-a4af-7e57ee2569a9)

**Comment by 31b4** [comment] 2023-11-09 01:40
With the premium questions on screen refresh the page (more times if needed) until the text color is green.
<img width="361" alt="image" src="https://github.com/31b4/Leetcode-Premium-Bypass/assets/75566095/83e51dfb-9ded-4849-a7a3-88a0c1638514">


Occasionally, the questions load slowly, and the unlocker script doesn't wait for them to fully load. I will work on resolving this issue.

**Comment by Yousuf-Gazi** [comment] 2023-11-11 13:25
How can I see the ques?
![Screenshot_1](https://github.com/31b4/Leetcode-Premium-Bypass/assets/55175452/e27c6509-c361-4da1-801f-4ba8939ccd1e)

Also no matter how much I refresh the page the text colour doesn't become green.
![Screenshot_2](https://github.com/31b4/Leetcode-Premium-Bypass/assets/55175452/56c8b2da-8d3e-4cf6-812b-07dffb715ec9)

**Comment by 31b4** [comment] 2023-11-11 17:24
are you using chrome? Can you give me some detail? Because it works for me

**Comment by Yousuf-Gazi** [comment] 2023-11-11 22:18
Yes, I am using Chrome. I downloaded the following one and followed the procedure you mentioned in readme.
![Screenshot_3](https://github.com/31b4/Leetcode-Premium-Bypass/assets/55175452/7168bf59-dac2-4c0e-ab4c-fdfd2510f994)
Then I went to leetcode > problems > settings > premium ques it shows me frequency. it also shows. companies like this one 
![Screenshot_4](https://github.com/31b4/Leetcode-Premium-Bypass/assets/55175452/eb965c11-0501-489c-b1e4-e1ef38ec3a82)
But the problem is here
![Screenshot_5](https://github.com/31b4/Leetcode-Premium-Bypass/assets/55175452/4c25e6a0-bf04-44ea-8548-a56e9c9dbcd8)

**Comment by 31b4** [comment] 2023-11-12 00:59
@Yousuf-Gazi https://youtu.be/5oZMsPbBljo
i hope this will help, maybe the problem can be slow internet connection, because sometimes when its loading slowly its not working for me aswell.

**Comment by Yousuf-Gazi** [comment] 2023-11-12 13:45
@31b4  thank you so much for the video. i did the same way. its because of the internet connection I think. because just like you mentioned the script doesn't wait for the loading of ques.

**Comment by 31b4** [comment] 2023-11-12 16:59
@Yousuf-Gazi im gonna try to fix it, but dont have much time for it

**Comment by Yousuf-Gazi** [comment] 2023-11-13 11:04
If you fix it. it would be helpful. Thanks a lot for the video. :D

**Comment by 31b4** [comment] 2023-11-13 16:44
@Yousuf-Gazi fixed it, here is the new release: https://github.com/31b4/Leetcode-Premium-Bypass/releases/tag/1.0.1
lmk if you still have a problem

**Comment by Yousuf-Gazi** [comment] 2023-11-14 00:16
Perfect man. It's working. Thanks a lot.

**Comment by 31b4** [comment] 2023-11-14 21:25
@Yousuf-Gazi yeah, leetcode just changed something with the darkmode-ui, now it should work, download the latest release and lmk if its working fine or not.

**Comment by 31b4** [comment] 2023-11-15 22:26
open new issue if you have another issue, thanks for the help

**Closed by 31b4** 2023-11-15 22:26 UTC
